version: "3.9"

networks:
  minio_network:
    external: true

services:
  tcp_server:
    build: .
    container_name: uvloop-tcp-server
    volumes:
      - ./app:/app
      - ./certs:/certs:ro
    environment:
      TLS_CERT: /certs/server.crt
      TLS_KEY: /certs/server.key
      TLS_CA: /certs/ca.crt
    ports:
      - "8888:8888"
    restart: always
    networks:
      - minio_network
